# Site settings
title: 文卿的藏剑山庄 # 你的博客名字，可以定义修订
header-img: "img/1.jpg"
tagline: "cn"  
description: "君子如风，藏剑西湖"  # 一句话描述你的博客
baseurl: ""
url: "yaowenqing.com"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "文卿" # 填写作者信息：名字
  email: 812885759@qq.com # 填写作者信息：邮箱
  bio: "WHU软件工程本科学生" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Wenqing" # 你的名字
      header-img: "img/1.jpg" # We don't want posts without a header image, that whould mean white on white

# Sidebar settings

sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "WHU软件工程专业 姚文卿"
sidebar-avatar: /img/5.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags

featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 30              # A tag will be featured if the size of it is more than this condition value

# Links to include in footer navigation
